### ISSUE TITLE
 maxLineSize of 4096 exceeded!

### ISSUE THREAD

**Issue by xelax** [hseeberger/akka-sse#164]
when I read large SSE events I get this error (using RC3)

2016-12-09 15:37:01,504 ERROR a.s.i.i.FileSubscriber - Tearing down FileSink(updates.tsv) due to upstream error
java.lang.IllegalStateException: maxLineSize of 4096 exceeded!
	at de.heikoseeberger.akkasse.LineParser$$anon$1.onPush(LineParser.scala:66)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:484)

**Comment by hseeberger** [comment]
Just increase the limits:
https://github.com/hseeberger/akka-sse/blob/master/akka-sse/src/main/scala/de/heikoseeberger/akkasse/EventStreamUnmarshalling.scala#L52 and https://github.com/hseeberger/akka-sse/blob/master/akka-sse/src/main/scala/de/heikoseeberger/akkasse/EventStreamUnmarshalling.scala#L58
